#################################
#      Core Configuration       #
#       By BTTFHamsterZK        #
#################################
#(Everything has to have a #, or it will not be considered proper YAML. :D)

# There is no configuration yet, nor am I sure if there will ever be...

#################################
#        Core ReadME YML        #
#       By BTTFHamsterZK        #
#################################

#     Commands!
# First, There are these commands that are working currently.
## /help - This just overrides the vanilla /help command, making it custom!
## /plugins - Same reason as above.
## /info - This is just a color testing command, and doesn't actually obtain stats.
## /owners - This displays the owners, and what position they have.

#     Features!
#Second, These are the features that is in the plugin at the moment.
## Click-To-Cauldron - This serves no purpose at all, but was me just testing out listeners.
## Anti-TnT - This makes current placed TnT give 0 tile damage, and disallow current TnT's being placed.

#     Technical Features!
#Third, we have all of the technical, out of game accomplishments!
## Config.yml - I have successfully generated YMLs.
## Learning Listeners - I have used the Sneaking listener, and the ClickBlock listener. 
## I have actually made this thing.
## Made an onEnable, onDisable message in the console. 

#     Thank you for looking over the config.yml! 
